version: "3.9"

services:
  germanfastapi-backend:
    build: ./backend
    container_name: backend
    networks:
      default:
        aliases:
          - backend

  germanfastapi-frontend:
    build: ./frontend
    depends_on:
      - germanfastapi-backend
    ports:
      - "80:80"
    networks:
      default:
        aliases:
          - frontend

networks:
  default:
    driver: bridge